### PR TITLE
Private access visibility (follow-up to #47)

### PR DESCRIPTION
**Pull request by jodersky**
This picks up #47 by @mengxr , by adding a feature flag to optionally enable "strict access visibility" (please feel free to suggest a better name).

Closes #47

### CODE REVIEW

**Comment by mengxr** [comment]
@jodersky How about `hideQualifiedAccess`?

**Comment by jodersky** [comment]
I will add tests tests and rebase this PR on #71 once merged

**Comment by rkuhn** [comment]
feature LGTM, thanks @jodersky !

**Comment by ktoso** [comment]
Looks good, looking forward to a test and we'll merge :) Thanks @jodersky

**Comment by jodersky** [comment]
I implemented a very simple test in the latest commit. @mengxr , is this the kind of behaviour you expected, should I add some more tests?

**Comment by mengxr** [comment]
Yes. We also need to test package protected methods. Is it 100% safe to skip `val`s and `var`s?

**Comment by jodersky** [comment]
vals are currently always treated as public. The existing tests didn't verify that :/ I'll see how to fix it

**Comment by mengxr** [comment]
LGTM

**Comment by jodersky** [comment]
Latest commit adds more test cases and support for vals

**Comment by jodersky** [comment]
Rebased onto latest master and divided into logical commits.

The original intent was for this PR to get merged after #71, however since I rebased and to consolidate things, I am closing the aforementioned PR.

cddacd1a7427cc0c5a7577e3d39c0c8609d68bb2 corresponds to #70, remarks by @rkuhn taken into account

Let me know if you prefer distinct PRs

**Comment by jodersky** [comment]
travis, retest the please

**Comment by jodersky** [comment]
seems to be a bad travis cache, see #79

**Comment by 2m** [comment]
LGTM. PR validation passed after `travis cache --delete`

**Pull request merged**
