### PR TITLE
Support for 2.12.0

### PR DESCRIPTION
**Pull request by ktoso**
These reorderings make tests pass for me on 2.12.0.
No actual other changes

### CODE REVIEW

**Comment by SethTisue** [comment]
once this is merged we ought to be able to start running genjavadoc's test suite in the Scala community build again

**Comment by ktoso** [comment]
We can drop 2.10 in the build now right?

The problem really is just order of output AFAICS.

// cc @2m

**Comment by 2m** [comment]
But wouldn't the reorder mess up the tests that were passing with the original order?

I think the proper fix is to just rename [this](https://github.com/typesafehub/genjavadoc/blob/master/plugin/src/test/resources/patches/2.12.0-RC2.patch) to `2.12.0.patch`

**Comment by ktoso** [comment]
Oh, I totally missed that's how the test works - thanks @2m. Will do.
Yes it would break other tests - I PRed to get feedback :)

**Comment by ktoso** [comment]
JDK6 + Scala 2.12 failed - ofc because does not work at all. 
Fixed exclude.

**Pull request merged**
