### PR TITLE
Cross build on Scala 2.12.1

### PR DESCRIPTION
**Pull request by adriaanm**

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM

**Comment by ktoso** [comment]
I can release if if you want @adriaanm ?

**Comment by adriaanm** [comment]
That would be great, thanks! I've never done a release here.

**Comment by 2m** [comment]
Sorry for the late release. 0.10 jars for Scala 2.12.1 are on their way to Maven Central.

**Comment by adriaanm** [comment]
Thanks!

**Pull request merged**
