### PR TITLE
support Scala 2.13.0-M2

### PR DESCRIPTION
**Pull request by SethTisue**
also gratuitously bump sbt version, and fix a stray execute bit

### CODE REVIEW

**Comment by SethTisue** [comment]
@gmethvin assuming this looks good, would you mind publishing for M2, also? that would enable us to publish scala-java8-compat for M2.

**Comment by gmethvin** [comment]
I'm not familiar with the release process for this project. Last time @2m and @ktoso helped.

**Comment by SethTisue** [comment]
darn, Travis is red because ScalaTest hasn't published for M2 yet, and ScalaTest can't publish til ScalaCheck publishes, and Rickard is a new father and it's August so he's probably also on some epic European vacation

**Comment by 2m** [comment]
I can take care of the release once we figure out the upstream dependencies.

**Comment by patriknw** [comment]
Perhaps it would be good to transfer knowledge of releasing to other teams, since quick turnaround here is often important?

**Comment by ktoso** [comment]
Can we do a RELEASING.md here? I'm personally also sometimes confused how to release what project :)

**Comment by SethTisue** [comment]
> Can we do a RELEASING.md here? 

opened a separate ticket on that, #111

**Comment by SethTisue** [comment]
ScalaCheck is published for M2; waiting for ScalaTest now

**Comment by SethTisue** [comment]
@2m ScalaTest is now available for M2. can you publish genjavadoc now?

**Comment by SethTisue** [comment]
ScalaTest is now available for M2. I'm working on updating this PR.

**Comment by SethTisue** [comment]
the 2.11, 2.12, and 2.13 Jenkins runs are green, but the 2.10 ones fail

hey maintainers, would this be an opportune moment to simply drop 2.10 support? my guess is that 2.10 users will be fine using existing releases of genjavadoc and we don't need to keep releasing new versions for them

**Comment by SethTisue** [comment]
let's discuss the drop-2.10 topic on a new ticket, actually: #118

**Comment by SethTisue** [comment]
I have provisionally added a commit to this PR that drops 2.10 support, but I suggest we wait at least a few days before merging.

**Comment by SethTisue** [comment]
okay, let's merge it. but I don't have the rights to do myself

**Comment by 2m** [comment]
Artifacts for 2.13.0-M2 of genjavadoc 0.10 should be in Maven Central any time now.

**Pull request merged**
