### PR TITLE
Bump to Scala 2.12.0-RC2

### PR DESCRIPTION
**Pull request by retronym**
Performed with:

    git grep -l 2.12.0-RC1 | xargs perl -p -i -e 's/2.12.0-RC1/2.12.0-RC2/'

### CODE REVIEW

**Comment by retronym** [comment]
@2m Could you either merge this PR and publish a new version, or alternatively manually back-publish `com.typesafe.genjavadoc#genjavadoc-plugin_2.12.0-RC2;0.10` (the version I [need](https://github.com/scala/scala-java8-compat/pull/81) for scala-java8-compat.) ?

**Comment by ktoso** [comment]
Sure, gladly once it passes hm.
Currently failed on RC2: https://travis-ci.org/typesafehub/genjavadoc/jobs/168754833

There's some silly diff... we need to look at it. Can do tomorrow.

**Comment by retronym** [comment]
Thanks for investigating. I've used the RC1 build to release scala-java-compat_2.12.0-RC2, so this isn't super urgent.

**Comment by 2m** [comment]
Thanks @retronym. You missed one file, that had to be renamed to RC2. I fixed it here #91.

**Pull request closed without merging**
