### PR TITLE
Support 2.13.0-M1

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
Pushed another commit that removes the travis build matrix and uses `+test` / `crossScalaVersions` instead. This way Scala versions are only in one place. A downside is that there's no longer a separate travis build for each Scala version (compare https://travis-ci.org/typesafehub/genjavadoc/builds/225964667 and https://travis-ci.org/typesafehub/genjavadoc/builds/225966701)

**Comment by lrytz** [comment]
Hmm, the travis build got stuck while running `sbt +test` against the long list of Scala versions.

```
Java HotSpot(TM) 64-Bit Server VM warning: CodeCache is full. Compiler has been disabled.
Java HotSpot(TM) 64-Bit Server VM warning: Try increasing the code cache size using -XX:ReservedCodeCacheSize=
CodeCache: size=262144Kb used=260357Kb max_used=260378Kb free=1786Kb
 bounds [0x00007fab935aa000, 0x00007faba35aa000, 0x00007faba35aa000]
 total_blobs=62152 nmethods=61579 adapters=461
 compilation: disabled (not enough contiguous free space left)
```

**Comment by lrytz** [comment]
We can drop the second commit to avoid this problem for now.

**Comment by lrytz** [comment]
I can reproduce this locally, `+test` build gets slower and slower with each Scala version, even though I didn't get the `CodeCache is full` message. It's stuck for minutes here now:

```
[info] Setting version to 2.12.1
[info] Reapplying settings...
```

Here's a CPU usage profile from JMC:

image

Heap usage:

image


cc @dwijnand -- (running `sbt +test` with a long list of Scala versions) is it a known issue? in any case, this discussion should be moved somewhere else than this PR.

**Comment by dwijnand** [comment]
https://github.com/dwijnand/sbt-travisci is my solution to the scala version duplication problem.

**Comment by lrytz** [comment]
Removed the last commit, so this isn't held back.

**Comment by lrytz** [comment]
That would be great!

**Comment by 2m** [comment]
On its way to Maven Central.

**Pull request merged**
