### PR TITLE
Support Scala 2.12.3

### PR DESCRIPTION
**Pull request by gmethvin**

### CODE REVIEW

**Comment by ktoso** [comment]
Failure was unrelated `[error] (top/*:update) sbt.ResolveException: download failed: org.scala-lang#scala-library;2.10.4!scala-library.jar
`

**Comment by ktoso** [comment]
Should be also added to https://github.com/typesafehub/genjavadoc/blob/master/.travis.yml

**Comment by ktoso** [comment]
Added

**Comment by gmethvin** [comment]
@ktoso updated

**Comment by mushtaq** [comment]
Thanks for upgrading! Can you please publish the artefacts? cc/ @ktoso @gmethvin

**Comment by ktoso** [comment]
Yeah, we'll get to it tomorrow.

**Comment by 2m** [comment]
We've just back-released 0.10 for Scala 2.12.3. Will be in maven central any time now.

**Comment by ktoso** [comment]
Awesome, Thanks a lot Martynas :)

**Comment by mushtaq** [comment]
Thank you!

**Pull request merged**
